export default {
  SET_BENDING: 'SET_BENDING',
  INIT_TEETER: 'INIT_TEETER',
  INIT_FALLING_SHAPE: 'INIT_FALLING_SHAPE',
  SET_RIGHT_SIDE_SHAPES: 'SET_RIGHT_SIDE_SHAPES',
  SET_DROPPED_SHAPES: 'SET_DROPPED_SHAPES',
  SET_PLAY_PAUSE: 'SET_PLAY_PAUSE',
  SET_PLAY: 'SET_PLAY',
  SET_RESET: 'SET_RESET',
  SET_POSITION_Y: 'SET_POSITION_Y',
  SET_POSITION_X_LEFT: 'SET_POSITION_X_LEFT',
  SET_POSITION_X_RIGHT: 'SET_POSITION_X_RIGHT',
  SET_SPEED: 'SET_SPEED',
  SET_MODAL_SHOW: 'SET_MODAL_SHOW',
  SET_GAME_OVER: 'SET_GAME_OVER'
}
